kind: pipeline
type: docker
name: Maven插件


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


steps:
  - name: 代码
    image: dronestock/git

  - name: 编译
    image: pangum/drone
    settings:
      output: maven

  - name: 发布
    image: dronestock/docker
    privileged: true
    volumes:
      - name: cache
        path: /var/lib/docker
    settings:
      repository: dronestock/maven
      username: dronestock
      password:
        from_secret: token_docker


volumes:
  - name: cache
    host:
      path: /var/lib/cache/docker
